### PR TITLE
Revised README to correct database setup and special character handling

### PR DESCRIPTION
**Pull request by trand010**

### CODE REVIEW

**Review by MatejBozic — COMMENTED** [review]
I know the README mentions to navigate to the "correct" directory before inputting each part, but I don't think the user knows what the "correct" directory is yet. We need to tell them. For this reason, I recommend the following additions:

Right before the instruction to input `docker compose up -d` (line 34-ish), have an instruction to tell the user to navigate to the `db-dump` directory of the project directory.

Right before the instruction to input `npm i` (line 51-ish), have an instruction to tell the user to navigate to the `backend` directory of the project directory.

Right before the instruction to input `npm i` (line 57-ish), have an instruction to tell the user to navigate to the `frontend` directory of the project directory.

**Comment by anhoop89** [comment]
I've copied the database setup commands for Windows and tested them out. It worked for me as expected.

**Comment by MatejBozic** [comment]
Following the instructions on a mac got the program running correctly for me.

**Review by MatejBozic — APPROVED** [review]

**Comment by weswwolf** [comment]
special characters are working

**Pull request merged**
